const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(
  projectRoot,
  "assets",
  "bach-english-suite-no2-prelude-bwv807.mid"
);
const outputPath = path.join(
  projectRoot,
  "assets",
  "bach-english-suite-no2-prelude-bwv807-data.js"
);

const base64 = fs.readFileSync(sourcePath).toString("base64");
const chunks = base64.match(/.{1,100}/g) || [];
const output = `// Generated by tools/embed-midi.js. Do not edit this file by hand.
window.BACH_BGM_MIDI = Object.freeze({
  title: "English Suite No. 2 in A minor, BWV 807 — I. Prélude",
  composer: "Johann Sebastian Bach",
  base64: [
${chunks.map((chunk) => `    "${chunk}"`).join(",\n")}
  ].join("")
});
`;

fs.writeFileSync(outputPath, output, "utf8");
console.log(
  `Embedded ${fs.statSync(sourcePath).size} MIDI bytes into ${path.relative(
    projectRoot,
    outputPath
  )}.`
);
